version: "3"

services:
  visuanalytics:
    build: ./src
    restart: always
    ports:
      - 5000:8000
    volumes:
      - ./src/visuanalytics/out:/home/appuser/visuanalytics/out
      - ./src/visuanalytics/instance:/home/appuser/visuanalytics/instance
      - ./src/visuanalytics/resources:/home/appuser/visuanalytics/resources
      - ./src/visuanalytics/resources/images:/home/appuser/visuanalytics/resources/images
